# -*- coding: utf-8 -*-
"""Exp4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YyOnk-i0LA2BQRz4iJstW5hWuePtGMoV
"""

pip install openai

print("College Admission Chatbot")
print("Type 'exit' to stop.")
print("--------------------------------")

while True:
    user_input = input("Student: ").lower()

    if user_input == "exit":
        print("Chatbot: Thank you! Goodbye.")
        break

    if "course" in user_input:
        print("Chatbot: We offer B.Tech programs in Computer Science, IT, Electronics, and Mechanical Engineering.")

    elif "eligibility" in user_input:
        print("Chatbot: Students who have completed 12th standard with the required subjects are eligible to apply.")

    elif "fee" in user_input or "fees" in user_input:
        print("Chatbot: The tuition fee depends on the selected course. Please contact the college admission office for exact fees.")

    elif "admission" in user_input or "apply" in user_input:
        print("Chatbot: To apply, fill out the online application form, upload the required documents, and submit the application fee.")

    elif "document" in user_input:
        print("Chatbot: Common documents include 10th and 12th marksheets, ID proof, photographs, and transfer certificate.")

    else:
        print("Chatbot: Sorry, I can answer questions about courses, eligibility, fees, documents, and admission procedures.")

    print("--------------------------------")