# -*- coding: utf-8 -*-
"""exp5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/128W4g6MrXyvH2xSp-x5hc8tNSN61OcWS
"""

print("Medical Symptom Checker")
print("Type 'exit' to stop.")
print("--------------------------------")

rules = {
    "Flu": {
        "fever", "cough", "body pain", "headache", "fatigue", "cold"
    },

    "Common Cold": {
        "cough", "sore throat", "runny nose", "sneezing", "cold", "headache"
    },

    "Migraine": {
        "headache", "nausea", "sensitivity to light"
    },

    "Stomach Infection": {
        "stomach pain", "vomiting", "diarrhea", "fever"
    },

    "Allergy": {
        "sneezing", "runny nose", "itchy eyes"
    }
}

# Convert common user inputs to standard symptoms
synonyms = {
    "body pains": "body pain",
    "body ache": "body pain",
    "body aches": "body pain",
    "throat pain": "sore throat",
    "cold": "cold",
    "running nose": "runny nose",
    "stomach ache": "stomach pain",
    "tummy pain": "stomach pain"
}

while True:

    user_input = input(
        "Enter symptoms separated by commas: "
    ).lower().strip()

    if user_input == "exit":
        print("Thank you. Goodbye!")
        break

    # Read symptoms
    symptoms = set()

    for symptom in user_input.split(","):
        symptom = symptom.strip()

        # Convert synonym to standard symptom
        if symptom in synonyms:
            symptom = synonyms[symptom]

        symptoms.add(symptom)

    results = []

    # Rule-based reasoning
    for illness, illness_symptoms in rules.items():

        matched = symptoms.intersection(illness_symptoms)

        if len(matched) >= 2:
            results.append(
                (illness, matched, len(matched))
            )

    # Display results
    if results:

        results.sort(
            key=lambda x: x[2],
            reverse=True
        )

        print("\nPossible conditions:")

        for illness, matched, count in results:
            print(
                f"- {illness} "
                f"(matched symptoms: {', '.join(matched)})"
            )

    else:
        print("\nNo matching condition found.")

    print("\nNote: This is an educational rule-based system,")
    print("not a medical diagnosis.")
    print("--------------------------------")