# -*- coding: utf-8 -*-
"""Exp6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lnVDr-W5hzFDZa7CaJiv2jJlXebhQBYK
"""

print("Personalized Learning Assistant")
print("Type 'exit' to stop.")
print("--------------------------------")

student_name = input("Enter your name: ")

print("\nChoose your learning preference:")
print("1. Simple explanation")
print("2. Detailed explanation")
print("3. Explanation with examples")

choice = input("Enter choice: ")

if choice == "1":
    preference = "simple"
elif choice == "2":
    preference = "detailed"
else:
    preference = "examples"

previous_questions = []

print("\nHello", student_name + "!")
print("I will remember your learning preference:", preference)
print("--------------------------------")


answers = {
    "machine learning":
        "Machine Learning is a branch of AI that allows computers to learn from data and make predictions or decisions.",

    "supervised learning":
        "Supervised learning is a type of machine learning where a model learns from labelled data. For example, predicting house prices from previous house data.",

    "unsupervised learning":
        "Unsupervised learning finds patterns in data without labelled outputs. Clustering is a common example.",

    "python":
        "Python is a high-level programming language commonly used for web development, data science, AI, and automation.",

    "artificial intelligence":
        "Artificial Intelligence is the field of creating systems that can perform tasks that normally require human intelligence, such as reasoning and learning.",

    "neural network":
        "A neural network is a machine learning model inspired by the human brain. It consists of connected nodes called neurons.",

    "deep learning":
        "Deep Learning is a part of machine learning that uses neural networks with multiple layers to learn complex patterns."
}


while True:

    question = input("\nStudent: ").lower().strip()

    if question == "exit":
        print("\nAssistant: Goodbye", student_name + "!")
        break

    previous_questions.append(question)

    answer = None

    for topic in answers:
        if topic in question:
            answer = answers[topic]
            break

    if answer is None:
        answer = "Sorry, I don't know the answer to that question yet."

    if preference == "simple":
        print("\nAssistant:", answer)

    elif preference == "detailed":
        print("\nAssistant:", answer)
        print("You can ask me another question about this topic for more details.")

    elif preference == "examples":
        print("\nAssistant:", answer)

        if "machine learning" in question:
            print("Example: A system can learn from previous house prices and predict the price of a new house.")

        elif "supervised learning" in question:
            print("Example: Email spam detection using labelled spam and non-spam emails.")

        elif "python" in question:
            print("Example: Python can be used to write programs for data analysis and AI.")

        elif "artificial intelligence" in question:
            print("Example: Voice assistants and recommendation systems use AI.")

    print("\n[Agent Memory]")
    print("Student:", student_name)
    print("Learning preference:", preference)
    print("Previous questions:", len(previous_questions))